name: 问题询问
description: 例如问题询问专用通道
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        询问问题的好地方！
        （感谢您没有选择bug反馈！）
  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 通过联系方式告诉您问题答案！
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: 要询问我的问题？
      description: 告诉我，您在使用PasswordManager软件时想询问的问题？
      placeholder: ex. 密码解锁的的原理是什么？[这位使用者厉害了！(来自作者的调侃)]
    validations:
      required: true